language: python
cache: pip

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
matrix:
  fast_finish: true
  include:
    - python: 3.7
    - python: 3.6
    - python: 3.8
    - python: 3.9

install:
 - pip install -U pip
 - pip install -U flake8
 - pip install -U black

script:
 # Static analysis
 - flake8 --statistics --count
 - black --check --diff .
